# Generated by Django 3.2.6 on 2021-12-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20170424_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
